[package]
name = "ai2048"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.18.0", features = ["ndarray"] }
clap = { version = "4.5.49", features = ["derive"] }
crossterm = "0.29.0"
rand = "0.9.2"
